using DataAccess.Enum;
using DataAccess.Models;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Text;
using System.Threading.Tasks;
using Zen.DbAccess.Extensions;
using Zen.DbAccess.Factories;
using Zen.DbAccess.Models;

namespace DataAccess.Repositories;

public class OraclePeopleRepository : PeopleRepository, IPeopleRepository
{
    public OraclePeopleRepository(
        [FromKeyedServices(DataSourceNames.Oracle)] IDbConnectionFactory dbConnectionFactory)
        : base (dbConnectionFactory)
    {
    }
    public override async Task CreateTablesAsync()
    {
        if (await TableExistsAsync(TABLE_NAME))
            return;

        string sql = $"""
            create table {TABLE_NAME} (
                id number generated by default as identity not null,
                first_name varchar2(128),
                last_name varchar2(128) not null,
                type number,
                image blob,
                constraint person_pk primary key (id)
            )
            """;

        _ = await sql.ExecuteNonQueryAsync(_dbConnectionFactory);
    }

    public override async Task DropTablesAsync()
    {
        if (await TableExistsAsync(TABLE_NAME))
            return;

        string sql = $"""
            drop table {TABLE_NAME}
            """;

        _ = await sql.ExecuteNonQueryAsync(_dbConnectionFactory);
    }

    private async Task<bool> TableExistsAsync(string table)
    {
        int idx = table.IndexOf(".");
        var sqlParams = new List<SqlParam>();

        string sql = $"""
            select case when exists(
                select 1 from all_tables where table_name = upper(@sTableName) and owner =
            """;

        sqlParams.Add(new SqlParam("@sTableName", idx >= 0 ? table.Substring(idx + 1) : table));

        if (idx >= 0)
        {
            sql += $" upper(@sOwner) ";
            sqlParams.Add(new SqlParam("@sOwner", table.Substring(0, idx)));
        }
        else
        {
            sql += $" SYS_CONTEXT('USERENV', 'CURRENT_USER') ";
        }

        sql += $"""
            ) then 1 else 0 end as table_exists
            from dual
            """;

        var tableExists = await sql.QueryRowAsync<OracleTableExistsModel>(
            _dbConnectionFactory,
            sqlParams.ToArray()
        );

        if (tableExists != null && tableExists.TableExists)
            return true;

        return false;
    }
}
