using DataAccess.Enum;
using DataAccess.Models;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Text;
using System.Threading.Tasks;
using Zen.DbAccess.Extensions;
using Zen.DbAccess.Factories;
using Zen.DbAccess.Models;

namespace DataAccess.Repositories;

public class OraclePeopleRepository : PostgresqlPeopleRepository, IPeopleRepository
{
    protected override string TABLE_NAME { get; set; } = "svm.person";

    protected override string P_GET_ALL_PEOPLE { get; set; } = "svm.p_get_all_people";

    public OraclePeopleRepository(
        [FromKeyedServices(DataSourceNames.Oracle)] IDbConnectionFactory dbConnectionFactory)
        : base (dbConnectionFactory)
    {
    }
    public override async Task CreateTablesAsync()
    {
        if (!(await TableExistsAsync(TABLE_NAME)))
        {
            string sql = $"""
                create table {TABLE_NAME} (
                    id number generated by default as identity not null,
                    first_name varchar2(128),
                    last_name varchar2(128) not null,
                    birth_date date,
                    type number,
                    image blob,
                    created_at timestamp,
                    updated_at timestamp,
                    constraint person_pk primary key (id)
                )
                """;

            _ = await sql.ExecuteNonQueryAsync(_dbConnectionFactory!);
        }

        if (!(await TableExistsAsync(P_GET_ALL_PEOPLE)))
        {
            string sql = $"""
                create or replace procedure {P_GET_ALL_PEOPLE} is
                  lError   number := 0;
                  sError   varchar2(512) := '';
                  v_cursor sys_refcursor;
                begin
                	OPEN v_cursor FOR
                	select
                        id
                        , first_name
                        , last_name
                        , type
                        , birth_date
                        , image
                        , created_at
                        , updated_at
                        , lError as is_error
                        , sError as error_message
                    from svm.person 
                   order by id;

                	dbms_sql.return_result(v_cursor);
                end;
                """;

            _ = await sql.ExecuteNonQueryAsync(_dbConnectionFactory!);
        }
    }

    public override async Task DropTablesAsync()
    {
        if (await TableExistsAsync(TABLE_NAME))
        {
            string sql = $"""
                drop table {TABLE_NAME}
                """;

            _ = await sql.ExecuteNonQueryAsync(_dbConnectionFactory!);

            sql = $"""
                drop procedure {P_GET_ALL_PEOPLE}
                """;

            _ = await sql.ExecuteNonQueryAsync(_dbConnectionFactory!);
        }
    }

    private async Task<bool> TableExistsAsync(string table)
    {
        int idx = table.IndexOf(".");
        var sqlParams = new List<SqlParam>();

        string sql = $"""
            select case when exists(
                select 1 from all_tables where table_name = upper(@sTableName) and owner =
            """;

        sqlParams.Add(new SqlParam("@sTableName", idx >= 0 ? table.Substring(idx + 1) : table));

        if (idx >= 0)
        {
            sql += $" upper(@sOwner) ";
            sqlParams.Add(new SqlParam("@sOwner", table.Substring(0, idx)));
        }
        else
        {
            sql += $" SYS_CONTEXT('USERENV', 'CURRENT_USER') ";
        }

        sql += $"""
            ) then 1 else 0 end as table_exists
            from dual
            """;

        var tableExists = await sql.QueryRowAsync<OracleTableExistsModel>(
            _dbConnectionFactory!,
            sqlParams.ToArray()
        );

        if (tableExists != null && tableExists.TableExists)
            return true;

        return false;
    }

    private async Task<bool> FunctionExistsAsync(string procedureName)
    {
        return await ProcedureExistsAsync(procedureName, "FUNCTION");
    }

    private async Task<bool> PackageExistsAsync(string procedureName)
    {
        return await ProcedureExistsAsync(procedureName, "PACKAGE");
    }

    private async Task<bool> ProcedureExistsAsync(string procedureName, string objectType = "PROCEDURE")
    {
        int idx = procedureName.IndexOf(".");
        var sqlParams = new List<SqlParam>();

        string sql = $"""
            select case when exists(
                select 1 from all_procedures where procedure_name = upper(@sProcName) and object_type = upper(@sObjectType) and owner =
            """;

        sqlParams.Add(new SqlParam("@sProcName", idx >= 0 ? procedureName.Substring(idx + 1) : procedureName));
        sqlParams.Add(new SqlParam("@sObjectType", objectType));

        if (idx >= 0)
        {
            sql += $" upper(@sOwner) ";
            sqlParams.Add(new SqlParam("@sOwner", procedureName.Substring(0, idx)));
        }
        else
        {
            sql += $" SYS_CONTEXT('USERENV', 'CURRENT_USER') ";
        }

        sql += $"""
            ) then 1 else 0 end as procedure_exists
            from dual
            """;

        var procedureExists = await sql.QueryRowAsync<OracleProcedureExistsModel>(
            _dbConnectionFactory!,
            sqlParams.ToArray()
        );

        if (procedureExists != null && procedureExists.ProcedureExists)
            return true;

        return false;
    }
}
