using DataAccess.Enum;
using DataAccess.Models;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Text;
using System.Threading.Tasks;
using Zen.DbAccess.Extensions;
using Zen.DbAccess.Factories;
using Zen.DbAccess.Models;

namespace DataAccess.Repositories;

public class OraclePeopleRepository : PeopleRepository, IPeopleRepository
{
    public OraclePeopleRepository(
        [FromKeyedServices(DataSourceNames.Oracle)] IDbConnectionFactory dbConnectionFactory)
        : base (dbConnectionFactory)
    {
    }
    public override async Task CreateTablesAsync()
    {
        string sql = $"""
            create table {TABLE_NAME} (
                id number generated by default as identity not null,
                first_name varchar2(128),
                last_name varchar2(128) not null,
                type number,
                image blob,
                constraint person_pk primary key (id)
            )
            """;

        _ = await sql.ExecuteNonQueryAsync(_dbConnectionFactory);
    }

    public override async Task DropTablesAsync()
    {
        string sql = $"""
            drop table {TABLE_NAME}
            """;

        _ = await sql.ExecuteNonQueryAsync(_dbConnectionFactory);
    }
}
